name : CI CD Deploy
on :
  push :
    branches:
          - main
env :
  imagename: "myjavaapp"
jobs:
  CICDjob:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: setup java on the runner
        uses: actions/setup-java@v4
        with :
          distribution: 'temurin'
          java-version: '17'
          cache : 'maven' 
      - name: Build MAVEN code
        run : mvn package
      - name: install docker 
        uses: docker/setup-docker-action@v4
      - name : login to docker 
        uses : docker/login-action@v4
        with :
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push image
        uses:  docker/build-push-action@v6
        with:
          context: .
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.imageName }}:latest 
      
            




          
          
